.TH REDEFINE 1 "Sep 2017" "ELF kickers 3.0"
.LO 1
.SH NAME
redefine \- modify the name of a dynamic symbols in an ELF object file (not perfect!).
.SH SYNOPSIS
.B redefine
[OPTIONS] FILE [SYMBOL ...]
.SH DESCRIPTION
.B redefine
edits an ELF object file by changing the name of dynamic symbols and rehash. Note that
.B redefine
modifies the object file directly.
.SH COPYRIGHT
Copyright \(co 2017, 2017 k1988
.IR <zhaohaiyang.1988@gmail.com> .
.P
License GPLv2+: GNU GPL version 2 or later. This is free software: you
are free to change and redistribute it. There is NO WARRANTY, to the
extent permitted by law.
